# See https://pre-commit.com for more information
repos:
  - repo: local
    hooks:
      - id: ruff-fix
        name: Ruff Lint Fix
        entry: ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: Ruff Format
        entry: ruff format .
        language: system
        types: [python]
